### ISSUE TITLE
ImportError: No module named util

### ISSUE THREAD

**Issue by AvantiShri** [kundajelab/genomelake#14]
I cloned genomelake and installed it, then tried to run the example code for creating a genomelake data source. I get:

```
Traceback (most recent call last):
  File "hg19.py", line 1, in <module>
    from genomelake.backend import extract_fasta_to_file
  File "/users/avanti/genomelake/genomelake/backend.py", line 12, in <module>
    from .util import makedirs
ImportError: No module named util
```

I'm using Python 2 (let me know if this is causing the issue and I can switch). The contents of `genomelake/genomelake` are:
```
backend.py  backend.pyc  extractors.py  __init__.py  __init__.pyc  util.c  util.pyx
```
So I am not sure why it's having trouble finding util. If I start a python shell in `genomelake/genomelake` and say `import util`, I get the same "No module named util" error.

**Comment by Avsecz** [comment]
it's tested with python 3 and 2: https://github.com/kundajelab/genomelake/blob/master/.circleci/config.yml#L61-L62

**Comment by AvantiShri** [comment]
Fixed it. The properly compiled version of genomelake was in `/users/avanti/genomelake/build/lib.linux-x86_64-2.7`, so I just had to add that to my PYTHONPATH (there's a `util.so` file in the genomelake that lives there, which is what was needed).

**Comment by AvantiShri** [comment]
It was a problem with paths. My PYTHONPATH was such that it was picking up the uncompiled genomelake folder rather than the compiled one.
