### ISSUE TITLE
Speed of genomelake vs. pyfasta for DNA sequence loading

### ISSUE THREAD

**Issue by AvantiShri** [kundajelab/genomelake#15]
Hi all,

@sofiakp, at Illumina, compared the speed of genomelake for loading sequence-only input to a combination of pyfasta and her own one-hot encoding code. She found genomelake to be consistently much slower (looks like it's slower by an order of magnitude). I was unable to find anything amiss - any thoughts? Screenshots below:

Code comparing genomelake vs. pyfasta:
<img width="756" alt="screen shot 2018-06-30 at 11 20 12 am" src="https://user-images.githubusercontent.com/2302598/42127526-9cf02120-7c57-11e8-86ca-1e806833e7c9.png">

Sofia's one-hot encoding code:
<img width="577" alt="screen shot 2018-06-30 at 11 03 58 am" src="https://user-images.githubusercontent.com/2302598/42127533-acaa99b0-7c57-11e8-8865-11d1863121ac.png">

**Comment by akundaje** [comment]
Would this work for real valued inputs? Signal tracks. Genomelake was
supposed to be slower than raw numpy arrays but greater compression and
faster than HDF5. I don't know if the benchmarking was done systematically
on different systems.

Anshul.

**Comment by akundaje** [comment]
Also I believe it was originally built for multimodal data - sequence,
multiple 1D real value tracks.

**Comment by csfoo** [comment]
The key here is that "in_memory=False" for GenomeLake. This means the bcolz
arrays are read from disk, so it's not surprising its slower than using an
in-memory numpy array, even after including the slow one-hot-encoding step.
Note that GenomeLake was originally designed for vplots and/or large
numbers of signal tracks where it is not possible to load everything in
memory, so you want it to only keep the parts that are frequently used (the
actual training set) in memory, which is done through the caching mechanism
of bcolz.

**Comment by csfoo** [comment]
Sorry I realized both are actually reading from disk. One difference could
be that for the fasta file, it's likely a contiguous block read. For bcolz,
depending on the size of the interval, the code has to traverse and read
multiple files (bcolz stores each compressed block in a file) which can
make things slower.

Other things to consider while benchmarking - depending on the use case,
you may want to preload the files into cache (which is if you have enough
memory for all the tracks), or flush the disk cache before benchmarking (to
emulate the case where you don't). You may find the vmtouch tool useful for
this (https://github.com/hoytech/vmtouch).

**Comment by AvantiShri** [comment]
Yeah I was going to say that pyfasta also never reads things into memory (from https://github.com/brentp/pyfasta: "Stores a flattened version of the fasta file without spaces or headers and uses either a mmap of numpy binary format or fseek/fread so the sequence data is never read into memory").

I will ask sofia to try it with in-memory=True, but since the default for the ArrayExtractor is in_memory=False, I think it should be mentioned on the quickstart page that this is in fact slower than pyfasta for sequence-only input (since the quickstart involves a sequence-only example).

**Comment by AvantiShri** [comment]
A few followup questions from Sofia:

1) I understand it's mostly designed for real valued data like bigwigs, where the alternatives would be, reading directly from the bigwig or pre-storing in an h5 and reading from there. So I'm guessing that it's faster than both of these alternatives?

2) How does caching work and is it going to be much slower if you read from many bigwigs at once (eg. if you have 100s of bigwigs open) or if you read completely randomly?

3) Does it help if all of your batch comes from the same chromosome?

**Comment by csfoo** [comment]
1. The main speed gain comes from lz4 which is much faster than the gzip
compression used in bigwig and default for h5, but there is some python
overhead in bcolz. Also if disk reading speed is the bottleneck you won't
see an improvement. You can use lz4 with h5 and that may be as fast, but I
haven't tried that.

2. If it doesn't fit in RAM, then yes it'll be much slower and depend on
your disk speed. The default caching in bcolz is only for the last read
chunk, but I have a version which caches everything ever seen.

3. It will help if it comes in the same compressed chunk, which is I think
100 ish kb; you can check this.

**Comment by AvantiShri** [comment]
Thanks. I will pass this on.
